eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:mima@localhost:8081/eureka/

server:
  port: 8085

spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411

feign:
  hystrix:
    enabled: true